CREATE TABLE "logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ts" bigint NOT NULL,
	"level" text NOT NULL,
	"logger" text NOT NULL,
	"message" text NOT NULL,
	"player_id" text,
	"account_id" text,
	"node_id" text,
	"action" text,
	"meta_json" jsonb
);
--> statement-breakpoint
CREATE INDEX "logs_ts_idx" ON "logs" USING btree ("ts");
--> statement-breakpoint
CREATE INDEX "logs_level_ts_idx" ON "logs" USING btree ("level","ts");
--> statement-breakpoint
CREATE INDEX "logs_player_ts_idx" ON "logs" USING btree ("player_id","ts");
--> statement-breakpoint
CREATE INDEX "logs_account_ts_idx" ON "logs" USING btree ("account_id","ts");
--> statement-breakpoint
CREATE INDEX "logs_node_ts_idx" ON "logs" USING btree ("node_id","ts");
