CREATE TABLE "world_log_entries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ts" bigint NOT NULL,
	"tick" bigint NOT NULL,
	"kind" text NOT NULL,
	"node_id" text NOT NULL,
	"viewer_id" text NOT NULL,
	"viewer_account_id" text,
	"viewer_name" text NOT NULL,
	"event_json" jsonb NOT NULL
);
--> statement-breakpoint
CREATE INDEX "world_log_entries_ts_idx" ON "world_log_entries" USING btree ("ts");
--> statement-breakpoint
CREATE INDEX "world_log_entries_viewer_ts_idx" ON "world_log_entries" USING btree ("viewer_id","ts");
--> statement-breakpoint
CREATE INDEX "world_log_entries_viewer_account_ts_idx" ON "world_log_entries" USING btree ("viewer_account_id","ts");
--> statement-breakpoint
CREATE INDEX "world_log_entries_node_ts_idx" ON "world_log_entries" USING btree ("node_id","ts");
