CREATE TABLE "analytics_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ts" bigint NOT NULL,
	"game_version" text NOT NULL,
	"account_id" text,
	"player_id" text,
	"node_id" text,
	"kind" text NOT NULL,
	"value" bigint,
	"meta_json" jsonb
);
--> statement-breakpoint
CREATE INDEX "analytics_events_ts_idx" ON "analytics_events" USING btree ("ts");
--> statement-breakpoint
CREATE INDEX "analytics_events_game_version_ts_idx" ON "analytics_events" USING btree ("game_version","ts");
--> statement-breakpoint
CREATE INDEX "analytics_events_kind_ts_idx" ON "analytics_events" USING btree ("kind","ts");
--> statement-breakpoint
CREATE INDEX "analytics_events_node_ts_idx" ON "analytics_events" USING btree ("node_id","ts");
--> statement-breakpoint
CREATE INDEX "analytics_events_account_ts_idx" ON "analytics_events" USING btree ("account_id","ts");
