// GENERATED by art/workbench/accents/anchors.mjs — do not edit by hand.
//
// Head anchor per player body, in 64px body-frame pixel space: the top centre of
// the head. Identity accents (fx/identityAccent.ts) place a prop's bottom-centre
// here so crests sit correctly on every body without hand-tuned offsets.
// Re-run the script after adding or recolouring bodies.

export interface HeadAnchor {
  /** Horizontal centre of the head, in 0..63 body-frame pixels. */
  x: number;
  /** Topmost opaque row of the silhouette, in 0..63 body-frame pixels. */
  y: number;
}

export const HEAD_ANCHORS: Record<string, HeadAnchor> = {
  'sprites/classes/classless.png': { x: 32, y: 1 },
  'sprites/classes/cadence.png': { x: 32.5, y: 2 },
  'sprites/classes/light_cadence.png': { x: 32.5, y: 2 },
  'sprites/classes/medium_cadence.png': { x: 32, y: 2 },
  'sprites/classes/heavy_cadence.png': { x: 32.5, y: 2 },
  'sprites/classes/cooldown.png': { x: 32.5, y: 1 },
  'sprites/classes/light_cooldown.png': { x: 33, y: 2 },
  'sprites/classes/medium_cooldown.png': { x: 32, y: 1 },
  'sprites/classes/heavy_cooldown.png': { x: 32, y: 1 },
  'sprites/classes/dot.png': { x: 32.5, y: 2 },
  'sprites/classes/light_dot.png': { x: 31, y: 1 },
  'sprites/classes/medium_dot.png': { x: 32, y: 4 },
  'sprites/classes/heavy_dot.png': { x: 33, y: 2 },
  'sprites/classes/reload.png': { x: 32.5, y: 2 },
  'sprites/classes/light_reload.png': { x: 32.5, y: 2 },
  'sprites/classes/medium_reload.png': { x: 32.5, y: 1 },
  'sprites/classes/heavy_reload.png': { x: 32, y: 2 },
  'sprites/classes/energy.png': { x: 33, y: 4 },
  'sprites/classes/light_energy.png': { x: 33, y: 2 },
  'sprites/classes/medium_energy.png': { x: 34, y: 4 },
  'sprites/classes/heavy_energy.png': { x: 33, y: 2 },
  'sprites/classes/summoner.png': { x: 32.5, y: 2 },
  'sprites/classes/light_summoner.png': { x: 31, y: 3 },
  'sprites/classes/medium_summoner.png': { x: 32.5, y: 2 },
  'sprites/classes/heavy_summoner.png': { x: 31, y: 2 },
};

/** Anchor for a body frame, falling back to the roster average if unknown. */
export function headAnchorFor(frame: string | null | undefined): HeadAnchor {
  return (frame && HEAD_ANCHORS[frame]) || { x: 32, y: 2 };
}
