const fs=require('fs'),path=require('path');const p=__dirname;const c=JSON.parse(fs.readFileSync(path.join(p,'final-correction/complete.json')));if(c.done!==10||c.failures.length||c.sourceDrift.length||c.harnessDrift)throw Error('final incomplete');const rows=JSON.parse(fs.readFileSync(path.join(p,'final-correction/summary.json')));const name={'cadence-root':'Striker original','cooldown-root':'Squire Offensive','summoner-root':'Conduit no Recover First'};const raw=rows.map(r=>JSON.parse(fs.readFileSync(path.join(p,'final-correction',r.file))));const table=raw.map(r=>'| '+name[r.job.classRoot]+' | '+r.job.nodeId.replace('node-t4-','')+' | '+r.job.seed+' | '+(r.mastery?.elapsedMs/60000).toFixed(2)+' | '+(r.death?'Death':r.plateau?'Plateau':'Mastery')+' |').join('\n');const summary=raw.map(r=>({id:r.job.id,minutes:r.mastery?.elapsedMs/60000??null,essence:Object.values(r.mastery?.gross??{}).reduce((a,b)=>a+b,0),cost3:Object.values(r.costs[3]).reduce((a,b)=>a+b,0),fund3:r.fundingTimes[3],death:!!r.death}));fs.writeFileSync(path.join(p,'final-funding.json'),JSON.stringify(summary,null,2));let file=path.join(p,'RESULTS.md'),s=fs.readFileSync(file,'utf8');s=s.replace('## Why the original range was so wide',`## Final confirmation and recommendation

After the initial correction, a second fresh batch increased the T4-only XP factors slightly to **Tundra ×1.8 / Desert ×2.4**. The 600k segment stays unchanged. The table below is the final-factor evidence; the detailed 1.7/2.3 tables farther down are retained as the preceding experiment, not mislabeled as current values.

| Farming package | Node | Seed | Mastery minutes | Endpoint |
|---|---|---:|---:|---|
${table}

All ten final confirmations reached mastery without deaths, plateaus or runtime censors. These support a roughly **50–95-minute** window for the selected farming packages, close to the user's approximate 50–90 aim; the slowest rows still sit above 90. They do not establish this window for every viable build, every biome or the original defensive packages. Original Squire/Conduit policy variants were tested separately; defaults and player loadouts were not changed. Conduit Tundra's 65–66-minute policy result was at the earlier 1.7 factor and was not retested at 1.8.

**Recommendation:** keep these two biome XP corrections for candidate review, retain the tested farming-policy advice, and hold blanket adoption pending broader T4 node/class coverage and Volcanic approach/survival work. Do not ship 600k alone. If defensive setups must also fit within 90, this is not yet solved: the original slow packages need roughly another 20–30% effective throughput beyond the final reward adjustment. Measure Destroyer's execution delivery/overkill and Conduit's damage delivery/reconstruction in those exact matchups before choosing class coefficients; a universal reward increase would bring the fastest setups below target. Do not infer the same buff should apply to every specialization.

Essence at cap and +3 summed reference costs for this final batch are in [final funding](final-funding.json); no row fully funds all required colors. At a rough static level, local supply factors near Volcanic .085, Tundra .15 and Desert .23 (current .495) would bring summed currency income closer to reference +3 costs, but these are **untested estimates**, not applied changes or a solution to off-color costs/catalysts/Global Mastery. No blanket T4 essence cut can be justified as equivalent across the corrected biomes.

The completed study now contains **48 fresh runs** (18 diagnostic + 20 correction/policy + 10 final confirmation). [Final receipt](final-correction/complete.json) records no process failures or source/harness drift; [final summary](final-correction/summary.json) and raw snapshots remain available. Final numeric reward-scope validation passed. Earlier full typecheck covered the same structure with 1.7/2.3; only the two numeric factors changed afterward. All experiments are local, unmerged and undeployed.

## Why the original range was so wide`);s=s.replace('38 fresh simulations, both batch receipts','38 fresh simulations in the first two batches (plus ten final confirmations above), both initial batch receipts');fs.writeFileSync(file,s);console.log('Final report generated');