import assert from 'node:assert/strict';
import { applyStatusEffect, type GameplayEvent } from '@mmo-idle/shared';
import { gameplayPlayerSlices as slices } from './fixtures/gameplayPlayer';
import { GameplayRecorder } from '../src/analytics/gameplayRecorder';
import { GameplayWriter } from '../src/analytics/gameplayWriter';
import { gameplayMetrics } from '../src/analytics/gameplayMetrics';
import { World } from '../src/world/World';
import { recordWorldLogEvent } from '../src/world/worldLog';
import { setAttackTarget } from '../src/systems/combat/ai/targeting';
import { adminAuthorized } from '../src/admin/auth';
import { registerPlayerHandlers, type PlayerHandlerDeps } from '../src/net/playerHandlers';


async function main() {
  let now = Date.now();
  const events: GameplayEvent[] = [];
  const world = new World();
  world.rewardMultiplier = 1;
  const player = world.attachPlayerEntity(slices('private-socket-id'), 'private-socket-id');
  player.isPlayer.name = 'PRIVATE DISPLAY NAME';
  const observer = world.attachPlayerEntity(slices('observer'), 'observer');
  const recorder = new GameplayRecorder(e => events.push(e), 'balance-test', () => now);
  world.gameplay = recorder;
  recorder.start(player, 'random-character-id', 'human');
  recorder.start(observer, 'random-observer-id', 'human');
  const initial = events[0];
  const handlers = new Map<string, (...args: any[]) => void>();
  const socket = { id: player.isPlayer.id, on: (key: string, fn: (...args: any[]) => void) => handlers.set(key, fn), emit: () => {} } as unknown as Parameters<typeof registerPlayerHandlers>[0];
  registerPlayerHandlers(socket, { world, db: {}, session: { accountId: 'PRIVATE ACCOUNT', characterId: 'PRIVATE CHARACTER' }, sessionsBySocket: new Map(), adminControls: { emitPlayerSummaries: () => {}, emitTelemetry: () => {} }, socketByAccount: new Map(), inactiveSockets: new Set(), sessionStartedAtBySocket: new Map(), recordSessionEnd: () => {}, emitBossFelledState: () => {} } as unknown as PlayerHandlerDeps);
  const decisions = () => events.filter(e => e.payload.kind === 'decision');
  handlers.get('inventory:equipItem')!('PRIVATE BAD REQUEST');
  handlers.get('player:unlockSkill')!('PRIVATE BAD REQUEST');
  assert.equal(decisions().length, 0, 'rejected actual socket handlers must not record choices');
  handlers.get('player:setAuto')!(true);
  assert.equal(decisions().length, 1, 'accepted actual handler records choice');
  handlers.get('player:setAuto')!(true);
  assert.equal(decisions().length, 1, 'no-op toggles do not inflate decision counts');
  recorder.decision(player, 'abilities', null, recorder.beforeDecision(player), true);
  assert.equal(decisions().length, 1, 'successful no-op loadout submissions do not inflate decisions');
  assert.equal(initial.payload.kind === 'session-start' && initial.payload.build.auto, false, 'snapshots cannot mutate after enqueue');

  const boss = world.createMonster(player.hasPosition.nodeId, 'crag-behemoth', { x: 450, y: 400 });
  assert(boss);
  const opts = { visibility: 'combat' as const, relatedPlayerIds: [player.isPlayer.id], nodeId: player.hasPosition.nodeId };
  recordWorldLogEvent(world, { kind: 'damage', nodeId: opts.nodeId, source: { id: player.isPlayer.id, name: player.isPlayer.name, actorType: 'player' }, target: { id: boss.isMonster.id, name: boss.isMonster.name, actorType: 'monster' }, hpDamage: 12, absorbed: 0, damageType: 'direct' }, opts);
  assert.equal(events.filter(e => e.payload.kind === 'encounter-start').length, 1, 'observer fanout must not create duplicate attempts');
  recordWorldLogEvent(world, { kind: 'damage', nodeId: opts.nodeId, source: { id: boss.isMonster.id, name: boss.isMonster.name, actorType: 'monster' }, target: { id: player.isPlayer.id, name: player.isPlayer.name, actorType: 'player' }, hpDamage: 8, absorbed: 0, damageType: 'direct' }, opts);
  applyStatusEffect(player.tracksCombat, { id: 'telemetry-poison', maxStacks: 5, remainingMs: 10_000 });
  now += 500;
  world.killPlayer(player.isPlayer.id, { kind: 'melee', killer: { monsterTypeId: boss.isMonster.monsterTypeId, monsterName: boss.isMonster.name, isBoss: true, nodeId: opts.nodeId }, damage: 8, abilityName: 'Boss slam' });
  const death = events.find(e => e.payload.kind === 'death')!.payload;
  assert(death.kind === 'death');
  assert(death.statuses.some(s => s.effectId === 'telemetry-poison'), 'capture before death clears statuses');
  assert.equal(death.build.auto, true, 'capture before death disables automation');
  assert.equal(death.recentDamage.length, 1);
  assert.equal(death.killerType, 'crag-behemoth');
  assert.equal(player.tracksCombat.statusEffects.length, 0, 'normal death cleanup still happens');
  const attempt = events.find(e => e.payload.kind === 'encounter-end')!.payload;
  assert(attempt.kind === 'encounter-end');
  assert.equal(attempt.outcome, 'death');
  assert.equal(attempt.damageDealt, 12);
  assert.equal(attempt.damageTaken, 8);
  assert(events.some(e => e.payload.kind === 'exposure' && e.payload.durationMs === 500));
  world.respawnPlayer(player.isPlayer.id);
  handlers.get('player:setAuto')!(true);
  assert.equal(decisions().at(-1)!.payload.kind === 'decision' && (decisions().at(-1)!.payload as any).afterFailure, 'death');

  setAttackTarget(world, player, boss.isMonster.id);
  now += 1_000; recorder.sample(world, now);
  recorder.stop(player.isPlayer.id, 'disconnect', player);
  assert.equal((events.filter(e => e.payload.kind === 'encounter-end').at(-1)!.payload as any).outcome, 'disconnect');
  recorder.start(player, 'random-character-id', 'human');
  const starts = events.filter(e => e.characterId === 'random-character-id' && e.payload.kind === 'session-start');
  assert.notEqual(starts[0].sessionId, starts[1].sessionId, 'reconnect keeps character identity but changes session');
  now += 1_000; recorder.sample(world, now);
  recordWorldLogEvent(world, { kind: 'kill', nodeId: opts.nodeId, killer: { id: observer.isPlayer.id, name: observer.isPlayer.name, actorType: 'player' }, victim: { id: boss.isMonster.id, name: boss.isMonster.name, actorType: 'monster' }, damage: 12 }, opts);
  assert.equal((events.filter(e => e.payload.kind === 'encounter-end').at(-1)!.payload as any).outcome, 'victory', 'another player killing the engaged boss closes the attempt');
  recorder.markTest(player.isPlayer.id);
  handlers.get('player:setAuto')!(false);
  assert.equal(decisions().at(-1)!.cohort, 'test');
  setAttackTarget(world, player, boss.isMonster.id);
  now += 1_000; recorder.sample(world, now);
  setAttackTarget(world, player, null);
  now += 10_001; recorder.sample(world, now);
  assert.equal((events.filter(e => e.payload.kind === 'encounter-end').at(-1)!.payload as any).outcome, 'retreat');
  setAttackTarget(world, player, boss.isMonster.id);
  now += 1_000; recorder.sample(world, now);
  recorder.shutdown();
  assert.equal((events.filter(e => e.payload.kind === 'encounter-end').at(-1)!.payload as any).outcome, 'interrupted');
  const json = JSON.stringify(events);
  for (const forbidden of ['PRIVATE', 'private-socket-id', 'accountId', 'displayName', 'monsterEntityId', 'ownerPlayerId']) assert(!json.includes(forbidden), `privacy projection leaked ${forbidden}`);
  assert.equal(gameplayMetrics(events.find(e => e.payload.kind === 'death')!).filter(m => m.metric === 'deaths').length, 1);
  assert(!JSON.stringify(events.flatMap(gameplayMetrics)).includes('random-character-id'), 'daily aggregates contain no character identity');

  let attempts = 0;
  const batches: string[][] = [];
  const writer = new GameplayWriter(async batch => { batches.push(batch.map(e => e.id)); if (++attempts === 1) throw new Error('temporary'); }, () => now, 2);
  writer.enqueue(initial); writer.enqueue(events[1]); writer.enqueue(events[2]);
  assert.equal(writer.status().dropped, 1, 'capacity stays bounded');
  await Promise.all([writer.flush(), writer.flush()]);
  assert.equal(attempts, 1, 'only one insert in flight');
  assert.equal(writer.status().queued, 2, 'failed batch retained');
  await writer.flush(); assert.equal(attempts, 1, 'retry uses backoff');
  now += 1_000; await writer.flush();
  assert.deepEqual(batches[0], batches[1], 'retry keeps stable IDs');
  assert.equal(writer.status().queued, 0);
  writer.enqueue(initial); now += 600_001; await writer.flush();
  assert.equal(writer.status().dropped, 2, 'expired evidence counted as lost');
  assert.equal(adminAuthorized(undefined, undefined, true), false);
  assert.equal(adminAuthorized('short', 'short', true), false);
  assert.equal(adminAuthorized('x'.repeat(32), 'x'.repeat(32), true), true);
  assert.equal(adminAuthorized('y'.repeat(32), 'x'.repeat(32), true), false);
  assert.equal(adminAuthorized(undefined, undefined, false), true);
  console.log('gameplayTelemetry.test.ts: ok');
}
void main().catch(err => { console.error(err); process.exitCode = 1; });
