import { GAME_CONFIG } from "../config/gameConfig";
import type { HitboxRect } from "../hitbox/types";
import { generateJungleNodeTrees } from "./jungleTrees";
import { isOnForestPath } from "./forestPaths";
import { NODE_BIOMES } from "./nodeBiomes";
import type { NodeFeatureShape } from "./nodeFeatures";
import { generatePlainsNodeTrees } from "./plainsTrees";
import { generateSwampNodeTrees } from "./swampTrees";
import { generateTundraNodeTrees, generateWastelandNodeTrees } from "./deadTrees";

// ─── Scattered forest trees ───────────────────────────────────────────────────
//
// Trees are generated deterministically per node from the node id, so the server
// (movement blocking) and every client (rendering + collision overlay) agree on
// the exact same layout without any network traffic. The art lives in a 2×2
// sprite sheet (`trees.png`); each of the four cells is one tree variant.
//
// The trunk hitboxes below were baked from the matching `trees_hitbox.png` with
// the same greedy-rect-cover algorithm used for monster/player sprites, so the
// footprint hugs the actual trunk + roots instead of a loose circle. Regenerate
// with `pnpm --filter @mmo-idle/server bake:tree-hitboxes`.

/** Biome family that receives scattered trees. */
export const TREE_BIOME_GROUP = "forest";

/** Number of tree variants in the sheet (2×2 grid). */
export const TREE_VARIANT_COUNT = 4;

/** One tree cell is 1024×1024 within the 2048×2048 sheet. */
export const TREE_CELL_PX = 1024;

/** Base on-screen size (node px) of a tree cell before per-tree size jitter. */
export const TREE_DISPLAY_BASE = 480;

export type TreeArtSet =
  | "forest"
  | "jungle"
  | "plains"
  | "swamp"
  | "tundra"
  | "wasteland"
  | "cave-rock"
  | "desert-rock"
  | "volcanic-rock"
  | "trench-rock";

/**
 * Baked trunk hitbox rects per variant, center-relative to the cell, in cell px.
 * Generated by `bake:tree-hitboxes` (greedy rect cover of `trees_hitbox.png`).
 */
export const TREE_HITBOX_RECTS: readonly (readonly HitboxRect[])[] = [
  // variant 0
  [
    { offsetX: -8, offsetY: 285, halfW: 87, halfH: 117 },
    { offsetX: 98, offsetY: 387, halfW: 19, halfH: 49 },
    { offsetX: -146, offsetY: 391, halfW: 49, halfH: 18 },
    { offsetX: -109, offsetY: 337, halfW: 15, halfH: 36 },
    { offsetX: -59, offsetY: 419, halfW: 31, halfH: 17 },
    { offsetX: 145, offsetY: 380, halfW: 29, halfH: 14 },
  ],
  // variant 1
  [
    { offsetX: -35, offsetY: 304, halfW: 70, halfH: 98 },
    { offsetX: 75, offsetY: 383, halfW: 41, halfH: 48 },
    { offsetX: -150, offsetY: 391, halfW: 45, halfH: 18 },
    { offsetX: -59, offsetY: 419, halfW: 31, halfH: 17 },
    { offsetX: 49, offsetY: 305, halfW: 15, halfH: 30 },
    { offsetX: 145, offsetY: 380, halfW: 30, halfH: 13 },
  ],
  // variant 2
  [
    { offsetX: -9, offsetY: 314, halfW: 88, halfH: 90 },
    { offsetX: 96, offsetY: 385, halfW: 18, halfH: 50 },
    { offsetX: -150, offsetY: 393, halfW: 47, halfH: 18 },
    { offsetX: -56, offsetY: 419, halfW: 33, halfH: 16 },
    { offsetX: -111, offsetY: 339, halfW: 14, halfH: 36 },
    { offsetX: 146, offsetY: 381, halfW: 32, halfH: 14 },
  ],
  // variant 3
  [
    { offsetX: 3, offsetY: 305, halfW: 76, halfH: 101 },
    { offsetX: 97, offsetY: 384, halfW: 18, halfH: 50 },
    { offsetX: -81, offsetY: 395, halfW: 8, halfH: 59 },
    { offsetX: 145, offsetY: 381, halfW: 31, halfH: 14 },
    { offsetX: -147, offsetY: 405, halfW: 42, halfH: 9 },
    { offsetX: -47, offsetY: 420, halfW: 26, halfH: 14 },
  ],
];

interface VariantFoot {
  /** Footprint bbox center offset from the cell center (cell px). */
  centerX: number;
  centerY: number;
  /** Footprint bbox half extents (cell px). */
  halfW: number;
  halfH: number;
  /** Top-most footprint edge offset from cell center (cell px). */
  top: number;
  /** Bottom-most footprint edge offset from cell center (cell px). */
  bottom: number;
}

/**
 * Trunk rect per variant — the single largest-area baked rect. Collision uses a
 * smooth convex shape fitted to this rect (see `generateNodeTrees`) instead of
 * the full jagged rect union: the thin root rects are drawn *under* the player
 * (walk-on ground), and a union of offset AABBs forms concave pockets that movers
 * snag in while rounding the trunk. A single convex ellipse has a unique outward
 * normal everywhere, so sliding around it is smooth and depenetration is
 * unambiguous — eliminating the whole class of "stuck going around a tree" bugs.
 */
const VARIANT_TRUNK: readonly HitboxRect[] = TREE_HITBOX_RECTS.map((rects) =>
  rects.reduce((best, r) =>
    r.halfW * r.halfH > best.halfW * best.halfH ? r : best,
  ),
);

/** Footprint bbox per variant — derived once from the baked rects. */
const VARIANT_FEET: readonly VariantFoot[] = TREE_HITBOX_RECTS.map((rects) => {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const r of rects) {
    minX = Math.min(minX, r.offsetX - r.halfW);
    maxX = Math.max(maxX, r.offsetX + r.halfW);
    minY = Math.min(minY, r.offsetY - r.halfH);
    maxY = Math.max(maxY, r.offsetY + r.halfH);
  }
  return {
    centerX: (minX + maxX) / 2,
    centerY: (minY + maxY) / 2,
    halfW: (maxX - minX) / 2,
    halfH: (maxY - minY) / 2,
    top: minY,
    bottom: maxY,
  };
});

/**
 * Render seam (frame row, cell px) per variant: the client draws each tree in
 * two passes split at this row. The top slice `[0, seam)` (canopy + trunk) is
 * y-sorted over the player for walk-behind; the bottom slice `[seam, cell)`
 * (trunk base + roots) is drawn under the player so they step on the roots.
 *
 * The seam sits at the *north edge of the collision footprint* so that a mover
 * stopped against the trunk (its body kept clear of the footprint by box-vs-box
 * collision) is fully inside the over-pass — i.e. completely behind the tree —
 * leaving no lower-body sliver poking out over the roots. The client extends each
 * crop slightly past this row so the two passes overlap and hide the split line.
 */
export const TREE_TRUNK_TOP_PX: readonly number[] = VARIANT_FEET.map((foot) =>
  Math.round(TREE_CELL_PX / 2 + foot.top),
);

export interface TreeInstance {
  id: string;
  artSet: TreeArtSet;
  /** Sheet cell index (0–3). */
  variant: number;
  /** Native square image/sheet-cell size used by client crop calculations. */
  cellPx: number;
  /** Source-image row where the walk-behind canopy pass meets the root pass. */
  trunkTopPx: number;
  /** Sprite (cell) center in node-local world px. */
  spriteX: number;
  spriteY: number;
  /** Square display size in node px. */
  displaySize: number;
  /** Trunk collision rects (node-local world px) — block both players and monsters. */
  shapes: NodeFeatureShape[];
  /**
   * Ground-contact Y (bottom of the trunk footprint) used for client y-sort so
   * entities north of the trunk render behind the tree and those south of it
   * render in front.
   */
  baseY: number;
}

// ── Deterministic RNG (per node) ──────────────────────────────────────────────

function hashString(str: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ── Generation ────────────────────────────────────────────────────────────────

/** Trunks stay this far from node edges so they never sit on gates/spawns. */
const EDGE_MARGIN = 280;
/** Extra clearance a trunk keeps from a forest trail (see world/forestPaths.ts). */
const TRUNK_PATH_CLEARANCE = 150;
/** Minimum distance between two trunk centers (keeps walkable gaps between trees). */
const MIN_TRUNK_SEPARATION = 440;
/**
 * CEILING on trees per forest node, not a fixed count — normal nodes draw a seeded
 * count in `[FOREST_TREES_MIN_PER_NODE, TREES_PER_NODE]` so one stretch of forest is
 * open and the next is thick, instead of all ten nodes carrying an identical 34.
 */
const TREES_PER_NODE = 40;
const FOREST_TREES_MIN_PER_NODE = 24;
/**
 * Forest dungeons ring their clearing with denser woodland.
 *
 * Was 5x, which put 170 trunks on a dungeon node at ~368px mean spacing — a wall
 * rather than a treeline, and the x2.25 node resize had quietly made it worse (it
 * was 75 trees before). 2x keeps the ring clearly denser than open forest while
 * staying somewhere you can fight and path through.
 */
const FOREST_DUNGEON_TREE_MULTIPLIER = 1.5;
/**
 * Radius of a forest dungeon's central clearing — no trunk may stand inside it.
 *
 * Raised sharply from a flat 760. At that size the trees read as a loose collection
 * scattered over most of the node with a small hole punched in it; the arena is
 * supposed to be the SHAPE, with the trees forming a rough circle around it and
 * filling out to the borders behind. A clearing this size is what makes the treeline
 * read as a ring rather than as scatter.
 *
 * Node-relative so it holds its proportion through any resize.
 */
const DUNGEON_CENTER_TREE_CLEAR_RADIUS = GAME_CONFIG.NODE_WIDTH * 0.32;

function treesForNode(
  nodeId: string,
  rng: () => number,
): { target: number; minSeparation: number } {
  const biome = NODE_BIOMES[nodeId];
  if (biome?.isDungeon) {
    // Dungeons stay a FIXED count: the clearing and its treeline are the shape a boss
    // node must read as, and varying the ring muddies it.
    const target = Math.round(TREES_PER_NODE * FOREST_DUNGEON_TREE_MULTIPLIER);
    const densityMult = target / TREES_PER_NODE;
    return {
      target,
      minSeparation: MIN_TRUNK_SEPARATION / Math.sqrt(densityMult),
    };
  }
  const target =
    FOREST_TREES_MIN_PER_NODE +
    Math.floor(rng() * (TREES_PER_NODE - FOREST_TREES_MIN_PER_NODE + 1));
  return { target, minSeparation: MIN_TRUNK_SEPARATION };
}

const treeCache = new Map<string, TreeInstance[]>();

function generateForestNodeTrees(nodeId: string): TreeInstance[] {
  const rng = mulberry32(hashString(`${nodeId}:trees`));
  const { target: treesPerNode, minSeparation } = treesForNode(nodeId, rng);
  const W = GAME_CONFIG.NODE_WIDTH;
  const H = GAME_CONFIG.NODE_HEIGHT;

  const trees: TreeInstance[] = [];
  const anchors: Array<{ x: number; y: number }> = [];
  const maxAttempts = treesPerNode * 32;

  for (let i = 0; i < maxAttempts && trees.length < treesPerNode; i++) {
    const variant = Math.floor(rng() * TREE_VARIANT_COUNT) % TREE_VARIANT_COUNT;
    const foot = VARIANT_FEET[variant];
    const sizeMult = 0.85 + rng() * 0.4; // 0.85–1.25
    const displaySize = TREE_DISPLAY_BASE * sizeMult;
    const scale = displaySize / TREE_CELL_PX;

    // Footprint-center anchor in node-local world px.
    const footX = EDGE_MARGIN + rng() * (W - 2 * EDGE_MARGIN);
    const footY = EDGE_MARGIN + rng() * (H - 2 * EDGE_MARGIN);
    if (isInsideDungeonCenterClearing(nodeId, footX, footY)) continue;
    // Keep the trails walkable. Padded by roughly a trunk's own half-width so a tree
    // clears the path by its footprint rather than merely having its anchor outside
    // it — an unpadded test leaves trunks overhanging the trail edge.
    if (isOnForestPath(nodeId, footX, footY, TRUNK_PATH_CLEARANCE)) continue;

    const tooClose = anchors.some((a) => {
      const dx = footX - a.x;
      const dy = footY - a.y;
      return dx * dx + dy * dy < minSeparation * minSeparation;
    });
    if (tooClose) continue;

    const spriteX = footX - foot.centerX * scale;
    const spriteY = footY - foot.centerY * scale;

    // One smooth convex collision shape per tree, fitted to the trunk rect. Roots
    // are walk-on ground and intentionally do not block (see VARIANT_TRUNK).
    const trunk = VARIANT_TRUNK[variant];
    const shapes: NodeFeatureShape[] = [
      {
        kind: "ellipse",
        x: spriteX + trunk.offsetX * scale,
        y: spriteY + trunk.offsetY * scale,
        halfW: trunk.halfW * scale,
        halfH: trunk.halfH * scale,
      },
    ];
    if (treeIntersectsDungeonCenterClearing(nodeId, shapes)) continue;

    anchors.push({ x: footX, y: footY });
    trees.push({
      id: `${nodeId}:tree:${trees.length}`,
      artSet: "forest",
      variant,
      cellPx: TREE_CELL_PX,
      trunkTopPx: TREE_TRUNK_TOP_PX[variant] ?? TREE_CELL_PX,
      spriteX,
      spriteY,
      displaySize,
      shapes,
      baseY: spriteY + foot.bottom * scale,
    });
  }

  return trees;
}

function isInsideDungeonCenterClearing(
  nodeId: string,
  x: number,
  y: number,
): boolean {
  const biome = NODE_BIOMES[nodeId];
  if (!biome?.isDungeon) return false;
  const dx = x - GAME_CONFIG.NODE_WIDTH / 2;
  const dy = y - GAME_CONFIG.NODE_HEIGHT / 2;
  return dx * dx + dy * dy <
    DUNGEON_CENTER_TREE_CLEAR_RADIUS * DUNGEON_CENTER_TREE_CLEAR_RADIUS;
}

function treeIntersectsDungeonCenterClearing(
  nodeId: string,
  shapes: NodeFeatureShape[],
): boolean {
  const biome = NODE_BIOMES[nodeId];
  if (!biome?.isDungeon) return false;
  const cx = GAME_CONFIG.NODE_WIDTH / 2;
  const cy = GAME_CONFIG.NODE_HEIGHT / 2;
  const radiusSq =
    DUNGEON_CENTER_TREE_CLEAR_RADIUS * DUNGEON_CENTER_TREE_CLEAR_RADIUS;

  return shapes.some((shape) => {
    // Conservative bbox-vs-clearing test (covers rect and ellipse trunk shapes):
    // an ellipse never reaches past its bounding box, so a clear bbox is a clear
    // shape. Over-rejecting a tree near the clearing edge is harmless.
    const halfW = "halfW" in shape ? shape.halfW : shape.radius;
    const halfH = "halfH" in shape ? shape.halfH : shape.radius;
    const closestX = Math.max(shape.x - halfW, Math.min(cx, shape.x + halfW));
    const closestY = Math.max(shape.y - halfH, Math.min(cy, shape.y + halfH));
    const dx = closestX - cx;
    const dy = closestY - cy;
    return dx * dx + dy * dy < radiusSq;
  });
}

/** Deterministic biome-specific trees for a node. */
export function getNodeTrees(nodeId: string): TreeInstance[] {
  const cached = treeCache.get(nodeId);
  if (cached) return cached;

  const biome = NODE_BIOMES[nodeId];
  let trees: TreeInstance[] = [];
  if (biome?.biomeGroup === TREE_BIOME_GROUP) {
    trees = generateForestNodeTrees(nodeId);
  } else if (biome?.biomeGroup === "plains") {
    trees = generatePlainsNodeTrees(nodeId);
  } else if (biome?.biomeGroup === "jungle") {
    trees = generateJungleNodeTrees(nodeId);
  } else if (biome?.biomeGroup === "swamp") {
    trees = generateSwampNodeTrees(nodeId);
  } else if (biome?.biomeGroup === "tundra") {
    trees = generateTundraNodeTrees(nodeId);
  } else if (biome?.biomeGroup === "graveyard") {
    trees = generateWastelandNodeTrees(nodeId);
  }
  treeCache.set(nodeId, trees);
  return trees;
}
