import { GAME_CONFIG } from "../config/gameConfig";
import type { HitboxRect } from "../hitbox/types";
import { NODE_BIOMES } from "./nodeBiomes";
import type { NodeFeatureShape } from "./nodeFeatures";

// ─── Scattered forest trees ───────────────────────────────────────────────────
//
// Trees are generated deterministically per node from the node id, so the server
// (movement blocking) and every client (rendering + collision overlay) agree on
// the exact same layout without any network traffic. The art lives in a 2×2
// sprite sheet (`trees.png`); each of the four cells is one tree variant.
//
// The trunk hitboxes below were baked from the matching `trees_hitbox.png` with
// the same greedy-rect-cover algorithm used for monster/player sprites, so the
// footprint hugs the actual trunk + roots instead of a loose circle. Regenerate
// with `pnpm --filter @mmo-idle/server bake:tree-hitboxes`.

/** Biome family that receives scattered trees. */
export const TREE_BIOME_GROUP = "forest";

/** Number of tree variants in the sheet (2×2 grid). */
export const TREE_VARIANT_COUNT = 4;

/** One tree cell is 1024×1024 within the 2048×2048 sheet. */
export const TREE_CELL_PX = 1024;

/** Base on-screen size (node px) of a tree cell before per-tree size jitter. */
export const TREE_DISPLAY_BASE = 480;

/**
 * Baked trunk hitbox rects per variant, center-relative to the cell, in cell px.
 * Generated by `bake:tree-hitboxes` (greedy rect cover of `trees_hitbox.png`).
 */
export const TREE_HITBOX_RECTS: readonly (readonly HitboxRect[])[] = [
  // variant 0
  [
    { offsetX: -8, offsetY: 285, halfW: 87, halfH: 117 },
    { offsetX: 98, offsetY: 387, halfW: 19, halfH: 49 },
    { offsetX: -146, offsetY: 391, halfW: 49, halfH: 18 },
    { offsetX: -109, offsetY: 337, halfW: 15, halfH: 36 },
    { offsetX: -59, offsetY: 419, halfW: 31, halfH: 17 },
    { offsetX: 145, offsetY: 380, halfW: 29, halfH: 14 },
  ],
  // variant 1
  [
    { offsetX: -35, offsetY: 304, halfW: 70, halfH: 98 },
    { offsetX: 75, offsetY: 383, halfW: 41, halfH: 48 },
    { offsetX: -150, offsetY: 391, halfW: 45, halfH: 18 },
    { offsetX: -59, offsetY: 419, halfW: 31, halfH: 17 },
    { offsetX: 49, offsetY: 305, halfW: 15, halfH: 30 },
    { offsetX: 145, offsetY: 380, halfW: 30, halfH: 13 },
  ],
  // variant 2
  [
    { offsetX: -9, offsetY: 314, halfW: 88, halfH: 90 },
    { offsetX: 96, offsetY: 385, halfW: 18, halfH: 50 },
    { offsetX: -150, offsetY: 393, halfW: 47, halfH: 18 },
    { offsetX: -56, offsetY: 419, halfW: 33, halfH: 16 },
    { offsetX: -111, offsetY: 339, halfW: 14, halfH: 36 },
    { offsetX: 146, offsetY: 381, halfW: 32, halfH: 14 },
  ],
  // variant 3
  [
    { offsetX: 3, offsetY: 305, halfW: 76, halfH: 101 },
    { offsetX: 97, offsetY: 384, halfW: 18, halfH: 50 },
    { offsetX: -81, offsetY: 395, halfW: 8, halfH: 59 },
    { offsetX: 145, offsetY: 381, halfW: 31, halfH: 14 },
    { offsetX: -147, offsetY: 405, halfW: 42, halfH: 9 },
    { offsetX: -47, offsetY: 420, halfW: 26, halfH: 14 },
  ],
];

interface VariantFoot {
  /** Footprint bbox center offset from the cell center (cell px). */
  centerX: number;
  centerY: number;
  /** Footprint bbox half extents (cell px). */
  halfW: number;
  halfH: number;
  /** Top-most footprint edge offset from cell center (cell px). */
  top: number;
  /** Bottom-most footprint edge offset from cell center (cell px). */
  bottom: number;
}

/** Footprint bbox per variant — derived once from the baked rects. */
const VARIANT_FEET: readonly VariantFoot[] = TREE_HITBOX_RECTS.map((rects) => {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const r of rects) {
    minX = Math.min(minX, r.offsetX - r.halfW);
    maxX = Math.max(maxX, r.offsetX + r.halfW);
    minY = Math.min(minY, r.offsetY - r.halfH);
    maxY = Math.max(maxY, r.offsetY + r.halfH);
  }
  return {
    centerX: (minX + maxX) / 2,
    centerY: (minY + maxY) / 2,
    halfW: (maxX - minX) / 2,
    halfH: (maxY - minY) / 2,
    top: minY,
    bottom: maxY,
  };
});

/**
 * Render seam (frame row, cell px) per variant: the client draws each tree in
 * two passes split at this row. The top slice `[0, seam)` (canopy + trunk) is
 * y-sorted over the player for walk-behind; the bottom slice `[seam, cell)`
 * (trunk base + roots) is drawn under the player so they step on the roots.
 *
 * The seam sits at the *north edge of the collision footprint* so that a mover
 * stopped against the trunk (its body kept clear of the footprint by box-vs-box
 * collision) is fully inside the over-pass — i.e. completely behind the tree —
 * leaving no lower-body sliver poking out over the roots. The client extends each
 * crop slightly past this row so the two passes overlap and hide the split line.
 */
export const TREE_TRUNK_TOP_PX: readonly number[] = VARIANT_FEET.map((foot) =>
  Math.round(TREE_CELL_PX / 2 + foot.top),
);

export interface TreeInstance {
  id: string;
  /** Sheet cell index (0–3). */
  variant: number;
  /** Sprite (cell) center in node-local world px. */
  spriteX: number;
  spriteY: number;
  /** Square display size in node px. */
  displaySize: number;
  /** Trunk collision rects (node-local world px) — block both players and monsters. */
  shapes: NodeFeatureShape[];
  /**
   * Ground-contact Y (bottom of the trunk footprint) used for client y-sort so
   * entities north of the trunk render behind the tree and those south of it
   * render in front.
   */
  baseY: number;
}

// ── Deterministic RNG (per node) ──────────────────────────────────────────────

function hashString(str: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ── Generation ────────────────────────────────────────────────────────────────

/** Trunks stay this far from node edges so they never sit on gates/spawns. */
const EDGE_MARGIN = 280;
/** Minimum distance between two trunk centers (keeps walkable gaps between trees). */
const MIN_TRUNK_SEPARATION = 440;
/** Target number of trees per forest node. */
const TREES_PER_NODE = 11;
/** Forest dungeon nodes pack 5× as many trees (tighter trunk spacing). */
const FOREST_DUNGEON_TREE_MULTIPLIER = 5;

function treesForNode(nodeId: string): { target: number; minSeparation: number } {
  const biome = NODE_BIOMES[nodeId];
  if (biome?.isDungeon) {
    const target = TREES_PER_NODE * FOREST_DUNGEON_TREE_MULTIPLIER;
    const densityMult = target / TREES_PER_NODE;
    return {
      target,
      minSeparation: MIN_TRUNK_SEPARATION / Math.sqrt(densityMult),
    };
  }
  return { target: TREES_PER_NODE, minSeparation: MIN_TRUNK_SEPARATION };
}

const treeCache = new Map<string, TreeInstance[]>();

function generateNodeTrees(nodeId: string): TreeInstance[] {
  const { target: treesPerNode, minSeparation } = treesForNode(nodeId);
  const rng = mulberry32(hashString(`${nodeId}:trees`));
  const W = GAME_CONFIG.NODE_WIDTH;
  const H = GAME_CONFIG.NODE_HEIGHT;

  const trees: TreeInstance[] = [];
  const anchors: Array<{ x: number; y: number }> = [];
  const maxAttempts = treesPerNode * 32;

  for (let i = 0; i < maxAttempts && trees.length < treesPerNode; i++) {
    const variant = Math.floor(rng() * TREE_VARIANT_COUNT) % TREE_VARIANT_COUNT;
    const foot = VARIANT_FEET[variant];
    const sizeMult = 0.85 + rng() * 0.4; // 0.85–1.25
    const displaySize = TREE_DISPLAY_BASE * sizeMult;
    const scale = displaySize / TREE_CELL_PX;

    // Footprint-center anchor in node-local world px.
    const footX = EDGE_MARGIN + rng() * (W - 2 * EDGE_MARGIN);
    const footY = EDGE_MARGIN + rng() * (H - 2 * EDGE_MARGIN);

    const tooClose = anchors.some((a) => {
      const dx = footX - a.x;
      const dy = footY - a.y;
      return dx * dx + dy * dy < minSeparation * minSeparation;
    });
    if (tooClose) continue;

    const spriteX = footX - foot.centerX * scale;
    const spriteY = footY - foot.centerY * scale;

    const shapes: NodeFeatureShape[] = TREE_HITBOX_RECTS[variant].map((r) => ({
      kind: "rect",
      x: spriteX + r.offsetX * scale,
      y: spriteY + r.offsetY * scale,
      halfW: r.halfW * scale,
      halfH: r.halfH * scale,
    }));

    anchors.push({ x: footX, y: footY });
    trees.push({
      id: `${nodeId}:tree:${trees.length}`,
      variant,
      spriteX,
      spriteY,
      displaySize,
      shapes,
      baseY: spriteY + foot.bottom * scale,
    });
  }

  return trees;
}

/** Deterministic scattered trees for a node ('' for non-forest nodes). */
export function getNodeTrees(nodeId: string): TreeInstance[] {
  const cached = treeCache.get(nodeId);
  if (cached) return cached;

  const biome = NODE_BIOMES[nodeId];
  const trees =
    biome?.biomeGroup === TREE_BIOME_GROUP ? generateNodeTrees(nodeId) : [];
  treeCache.set(nodeId, trees);
  return trees;
}
