// Bakes per-body HEAD ANCHORS for identity accents (Stage 3).
//
// Run from repo root:
//   node art/workbench/accents/anchors.mjs
//
// Writes shared/src/sprites/headAnchors.ts — a generated map of
// atlas frame name -> { x, y } in 64px body-frame pixel space, marking the top
// centre of the head. The client places an accent prop's bottom-centre there,
// so a crest sits on the head of every body with no hand-tuned offsets.
//
// WHY BAKE RATHER THAN HARDCODE: the spread across the 24 bodies is small
// (topmost opaque row 1-4, head centre 30.5-34.0) because they all came from
// the same img2img chain at the same framing — but 3px at 64px is ~5% of the
// sprite, which is a visible slip on a prop sitting on the head. Baking also
// means new bodies (T3 refinements, paradigm-shift specs) pick up anchors by
// re-running this, instead of someone remembering to eyeball an offset.
//
// This is NOT the part-compositing the design docs rejected. That failed because
// EXTRACTING parts out of whole-canvas img2img output yields noise. Measuring
// where an existing sprite's head is, and placing a separately generated prop
// there, is a different and tractable problem.
import sharp from '../../../server/node_modules/sharp/lib/index.js';
import fs from 'node:fs';
import path from 'node:path';

const SRC = 'art/src/sprites/classes';
const OUT = 'shared/src/sprites/headAnchors.ts';
const ALPHA = 40;          // treat >40 as opaque; ignores faint glow fringes
const HEAD_PROBE_ROWS = 4; // rows below the crown used to find the head's width

const CLASSES = ['cadence', 'cooldown', 'dot', 'reload', 'energy', 'summoner'];
const FILES = ['classless.png', ...CLASSES.flatMap((c) => [
  `${c}.png`, `light_${c}.png`, `medium_${c}.png`, `heavy_${c}.png`,
])];

async function anchorOf(file) {
  const { data, info } = await sharp(file).ensureAlpha().raw()
    .toBuffer({ resolveWithObject: true });
  const at = (x, y) => data[(y * info.width + x) * 4 + 3];

  let topY = -1;
  for (let y = 0; y < info.height && topY < 0; y++) {
    for (let x = 0; x < info.width; x++) if (at(x, y) > ALPHA) { topY = y; break; }
  }
  if (topY < 0) return null;

  // Head width is measured a few rows down: the crown itself is often a single
  // stray pixel, which would bias the centre.
  const probe = Math.min(info.height - 1, topY + HEAD_PROBE_ROWS);
  let minX = info.width, maxX = -1;
  for (let x = 0; x < info.width; x++) {
    if (at(x, probe) > ALPHA) { if (x < minX) minX = x; if (x > maxX) maxX = x; }
  }
  if (maxX < 0) return null;
  return { x: Math.round(((minX + maxX) / 2) * 10) / 10, y: topY };
}

const rows = [];
for (const name of FILES) {
  const file = path.join(SRC, name);
  if (!fs.existsSync(file)) { console.warn('missing', name); continue; }
  const a = await anchorOf(file);
  if (a) rows.push([`sprites/classes/${name}`, a]);
}

const body = rows.map(([frame, a]) => `  '${frame}': { x: ${a.x}, y: ${a.y} },`).join('\n');
fs.writeFileSync(OUT, `// GENERATED by art/workbench/accents/anchors.mjs — do not edit by hand.
//
// Head anchor per player body, in 64px body-frame pixel space: the top centre of
// the head. Identity accents (fx/identityAccent.ts) place a prop's bottom-centre
// here so crests sit correctly on every body without hand-tuned offsets.
// Re-run the script after adding or recolouring bodies.

export interface HeadAnchor {
  /** Horizontal centre of the head, in 0..63 body-frame pixels. */
  x: number;
  /** Topmost opaque row of the silhouette, in 0..63 body-frame pixels. */
  y: number;
}

export const HEAD_ANCHORS: Record<string, HeadAnchor> = {
${body}
};

/** Anchor for a body frame, falling back to the roster average if unknown. */
export function headAnchorFor(frame: string | null | undefined): HeadAnchor {
  return (frame && HEAD_ANCHORS[frame]) || { x: 32, y: 2 };
}
`);

const xs = rows.map(([, a]) => a.x), ys = rows.map(([, a]) => a.y);
console.log(`wrote ${OUT} — ${rows.length} anchors`);
console.log(`  head centre x: ${Math.min(...xs)}..${Math.max(...xs)}  (spread ${(Math.max(...xs) - Math.min(...xs)).toFixed(1)}px)`);
console.log(`  crown y:       ${Math.min(...ys)}..${Math.max(...ys)}  (spread ${Math.max(...ys) - Math.min(...ys)}px)`);
